Upgrade SonarQube to 9.9.1
BCDevOps/sonarqube pull request #35
Opened 2023-05-16 17:45 UTC by bashbang

- Upgraded sonarqube to 9.9.1
- removed no longer needed log4j checks/cleanup
- added documentation for upgrade process.

2023-05-16 18:27 UTC, WadeBarnes requested changes
There are a few references to `8.2.2` that need to be updated to `9.9.1`.  Refer to the PR I've opened against your repo; https://github.com/bashbang/sonarqube/pull/1.

The Docker hub image has been built and pushed already.

2023-05-16 20:34 UTC, bashbang commented
@WadeBarnes changes accepted and included in PR

2023-05-17 12:05 UTC, WadeBarnes approved these changes

2023-05-17 12:08 UTC, WadeBarnes commented
@bashbang, Thanks.  I'll merge the PR and cut a release once my maintainer access has been restored.

2023-05-17 17:44 UTC, merged